[build]
  # Build command - installs dependencies and builds the frontend
  command = "cd frontend && npm install && npm run build"
  
  # Publish directory - where the built files are located
  publish = "frontend/build"
  
  # Functions directory (if using Netlify Functions later)
  functions = "netlify/functions"

[build.environment]
  # Node version for build
  NODE_VERSION = "18"
  
  # Enable legacy peer deps if needed
  NPM_FLAGS = "--legacy-peer-deps"

# API proxy redirects - proxy API calls to your backend
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200
  force = true

# SPA routing - redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"